### ISSUE TITLE
Decompose MUG into Sets (vs. Lists) to avoid any duplication

### ISSUE THREAD

**Issue by mpresteg** [nmdp-bioinformatics/ImmunogeneticDataTools#10]
This example results in multiple entries of HLA-B*35:02:01 after decomposition of mug.  Look into sets to avoid duplication (if appropriate).  Example GL String:

HLA-A*02:01:01:01+HLA-A*24:02:01:01/24:02:01:03^HLA-B*27:02:01+HLA-B*35:02:01/35:211^HLA-C*02:02:02+HLA-C*04:01:01:01/04:01:01:02/04:01:01:03/04:01:01:04/04:01:01:05/04:20/04:117^HLA-DPA1*01:03:01:01/01:03:01:02/01:03:01:03/01:03:01:04/01:03:01:05+HLA-DPA1*02:01:01^HLA-DPB1*04:01:01:01/04:01:01:02+HLA-DPB1*17:01^HLA-DQA1*02:01+HLA-DQA1*05:05:01:01/05:05:01:02/05:05:01:03/05:09/05:11^HLA-DQB1*02:02+HLA-DQB1*03:01:01:01/03:01:01:02/03:01:01:03^HLA-DRB1*07:01:01:01/07:01:01:02+HLA-DRB1*11:01:01^HLA-DRB3*01:01:02:01/01:01:02:02^HLA-DRB4*01:03:01:01/01:03:01:03

**Comment by kosoegawa** [comment]
Are you talking about ambiguity? Sorry, it is not clear to me what you meant by multiple entries of HLA-B*35:02:01.

**Comment by mpresteg** [comment]
Don't worry about this one.  It is an internal efficiency I want to look in to.

**Comment by mpresteg** [comment]
Resolved - Problem was not with Lists vs. Sets, but with the organizeByLocus method call needing to be moved outside of a loop within decomposeMug.
