### ISSUE TITLE
java.lang.ClassNotFoundException: javax.xml.bind.JAXBException

### ISSUE THREAD

**Issue by csmith-pact** [nmdp-bioinformatics/ImmunogeneticDataTools#106]
I am using the analyze-gl-strings `v0.9.1` tarball and get this with `openjdk 11.0.1 2018-10-16 LTS`. Can you advise?

```
(base) csmith@PPh-Staging-N02:~/git/ld-tools-0.0.1-SNAPSHOT$ bin/analyze-gl-strings -i ~/csmith/git/ImmunogeneticDataTools/ld-validation/src/test/resources/strictExample.txt
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/home/csmith/git/ld-tools-0.0.1-SNAPSHOT/lib/guice-3.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Jan 25, 2023 9:44:22 AM org.dash.valid.LinkageDisequilibriumAnalyzer detectLinkages
INFO: Processing gl string 1 of 1 (100%)
https://raw.githubusercontent.com/ANHIG/IMGTHLA/Latest/xml/hla_ambigs.xml.zip
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.nmdp.validation.tools.AnalyzeGLStrings.writeOutput(AnalyzeGLStrings.java:156)
	at org.nmdp.validation.tools.AnalyzeGLStrings.runAnalysis(AnalyzeGLStrings.java:108)
	at org.nmdp.validation.tools.AnalyzeGLStrings.call(AnalyzeGLStrings.java:99)
	at org.nmdp.validation.tools.AnalyzeGLStrings.main(AnalyzeGLStrings.java:233)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 4 more
```

**Comment by mpresteg** [comment]
That stack trace looks familiar.  Per my memory...the code was written some (many) years ago.  It initially targeted Java 6 and was maintained somewhat regularly through Java 8 as we added features, etc.

At some point, it got a bit dormant...we weren't adding new features, etc.

I finally revisited last summer and realized how many versions behind on Java it was.  I spent some days updating everything and getting it working on more modern Java, Maven and the like.

It appears I made the changes, tested them and released them...but - only to my personal repository.  I merged the changes to the public repository but it appears I never cut a new release.  I need to do that.  But - having gotten a new machine, may need some time to get my environment set up again.

In the meantime - see if you can make use of the later release on my personal repository here:  https://github.com/mpresteg/ImmunogeneticDataTools/releases/latest.

Thanks in advance for your patience.  May I ask - what's your use case?  I'm pleased to hear the software is being utilized.

Matt Prestegaard
***@***.***
(651) 334-5419
@mpresteg

Save our in-boxes! http://emailcharter.org
