### ISSUE TITLE
Articulate use case(s) for the Linkage Disequilibrium software

### ISSUE THREAD

**Issue by mpresteg** [nmdp-bioinformatics/ImmunogeneticDataTools#11]
@kosoegawa Could you provide a description of your primary use case (intended utilization) for this software?  I'd like to update the README.md with it and ensure there is clarity of purpose.  Without that, the code base may accidentally veer from it's original intent.

**Comment by kosoegawa** [comment]
HLA typing using Next Generation Sequencing (NGS) is becoming common practice in research and clinical lab settings.  HLA typing miscall occurs when DNA sequences from one of the alleles drop out.  HLA Linkage Disequilibrium Validation software was developed to identify common linkages between HLA-B and HLA-C, and HLA-DRB1, HLA-DRB3/4/5, HLA-DQA1 and HLA-DQB1.  This information is useful when HLA typing from NGS is reviewed.  The software not only validates known linkages, but also sends warning messages when unusual linkage was found.  The software user can find stronger evidences of the accuracy of his/her HLA typing results when common linkages are found.  Also the user can focus on reviewing the unusual HLA linkages whether these are true or likely generated from DNA sequencing dropouts.  The results of the software should be used for supporting the evidence, but not used to correct any HLA typing without confirmatory experiments.

**Comment by kosoegawa** [comment]
Please let me know the above description makes sense or not.

**Comment by mpresteg** [comment]
Beautiful!  Thank you.
