### ISSUE TITLE
Log files are not written to current directory

### ISSUE THREAD

**Issue by ghost** [nmdp-bioinformatics/ImmunogeneticDataTools#13]
When running the test data set

``` bash
$ mvn exec:java -Dexec.mainClass="org.dash.valid.LinkageDisequilibriumLoader" \
  -Dexec.args="resources/test/stanfordExamples.txt"
```

I wasn't sure it worked since I couldn't find `immuno.log` and `linkages.log`.  Later I found them in my home directory.

**Comment by mpresteg** [comment]
Resolved - Now writes to the current directory (vs. home directory).

**Comment by ghost** [comment]
Thanks!
