### ISSUE TITLE
call for paper in human immunology 

### ISSUE THREAD

**Issue by kosoegawa** [nmdp-bioinformatics/ImmunogeneticDataTools#14]
Hi Matt,
Steve Mack asked me whether we are interested in writing a paper about the program that we are working on. Steve is an editor-in-chief of Human Immunology. He said: Human Immunology is issuing an open call for papers, and invites you to contribute to our upcoming Special Issue on “Histocompatibility and Immunogenetic Data Resources,” which will be published in 2015.
He would like to have our work published in this special issue.
Are you interested in this? I am interested in, but this will give us a pressure to make this publicly available by the time of paper submission. The official dead line for the paper is the end of April, but he dais he can wait until the end of May. We have about 2.5 Months..... Please let me know.
Kazu

**Comment by kosoegawa** [comment]
In the 21st century, access to and application of a myriad of “Big Data” resources offers researchers and clinicians the ability accelerate research and discovery, and advance therapeutic care. Many structural, functional, genetic and genomic data resources are available for use in the histocompatibility and immunogenetics field. However, the scope and details of these resources, and the best approaches for applying them, may not be widely known. The developers and curators of these resources and the clinicians and researchers who make use of them possess essential knowledge for the advancement of the fields of human immunology. 

Human Immunology is issuing an open call for papers, and invites you to contribute to our upcoming Special Issue on “Histocompatibility and Immunogenetic Data Resources,” which will be published in 2015. 

Submissions will be accepted beginning on January 1, 2015 and through April 30, 2015.

Both original research articles and review articles describing data resources (e.g., public datasets and data repositories, databases, data formats, online tools and software platforms) pertinent to the histocompatibility and immunogenomics field, and the application of these resources for clinical and basic research may be submitted for this issue.

Invited topics include, but are not limited to: 
1   Leveraging functional, structural, genetic or genomic data resources for research and clinical applications
2   Approaches for accessing, managing and exchanging histocompatibility and immunogenetic data
3   Novel approaches to analyzing and reporting histocompatibility and immunogenetic “Big Data” 

Human Immunology is the official journal of the American Society of Histocompatibility and Immunogenetics, and publishes original research covering immunogenetics, innate and adaptive immunity, transplantation immunology, autoimmunity, infectious disease and tumor immunology. It is a peer-reviewed journal that offers authors an option for open-source publication.  The 2013 Thomson Reuters Impact Factor for Human Immunology is 2.298.

Manuscripts should be submitted online to the journal at http://ees.elsevier.com/him. Human Immunology’s Guide for Authors, detailing submission guidelines and polices, can be found at http://www.elsevier.com/journals/human-immunology/0198-8859/guide-for-authors. 

Please do not hesitate to contact us if you have any questions about this Special Issue or about Human Immunology.

Sincerely,

Wolfgang Helmberg, Guest Co-Editor
James Robinson, Guest Co-Editor
Jurgen Sauter, Guest Co-Editor
Steven J. Mack, Editor-In-Chief

**Comment by mpresteg** [comment]
Yes, I'm interested.  What do you believe we need to accomplish to be ready?

**Comment by kosoegawa** [comment]
I'm glad to hear. We will probably need more work to do.
The program has to be placed in public domain when it is published.
The program has to accept user's data.
We will need to perform vigorous tests from various data sets to reduce fails negative.
We will probably need to revise lookup table.
We will have a lot of work as we go, but it is very good thing to set dead line and goals instead of keep going and going.

**Comment by mpresteg** [comment]
Submitted 5/31/15
