### ISSUE TITLE
sample ID

### ISSUE THREAD

**Issue by kosoegawa** [nmdp-bioinformatics/ImmunogeneticDataTools#15]
Could we add sample ID for each GL string? Could we generate the output with sample ID?

**Comment by mpresteg** [comment]
I added a feature like this a couple of days ago.  I added some notes to the readme about the available inputs and outputs.  Note the portions related to CSV or tab-delimited files where the first column optionally represents an id.  This id (provided or generated based on file name) is included in the outputs to make verification of results simpler.  Let me know if it meets your expectations.
