### ISSUE TITLE
Support multiple HLA DB versions

### ISSUE THREAD

**Issue by mpresteg** [nmdp-bioinformatics/ImmunogeneticDataTools#18]
Allow specification of a particular HLA DB version (run time argument, api input, etc.).  Default to the latest if no input provided.

**Comment by kosoegawa** [comment]
Thanks! This is great!

**Comment by mpresteg** [comment]
Resolved:  Introduced support for HLA DB versions:  3.18, 3.15, 3.12, 3.11, 3.10.  Flexibility to add others over time.
