### ISSUE TITLE
Consider sorting the linkages according to frequency and rank

### ISSUE THREAD

**Issue by mpresteg** [nmdp-bioinformatics/ImmunogeneticDataTools#21]
"re-rank" or "prioritize" the race based on the frequencies and rank for each category.

**Comment by mpresteg** [comment]
@kosoegawa - Please specify criteria.

**Comment by kosoegawa** [comment]
I need to think more and perhaps talk to more people about this. Please leave the issue as it is for now. It is simple idea, but it may not be so simple to create criteria.

**Comment by mpresteg** [comment]
@kosoegawa - May we consider this closed?

**Comment by kosoegawa** [comment]
Yes 

Kazu 

Confidential; Protected under State of California Evidence Code Section 1157 
CONFIDENTIALITY NOTICE: E-mail may contain confidential information that is legally privileged. Do not read this e-mail if you are not the intended recipient. This e-mail transmission, and any documents, files or previous e-mail messages attached to it may contain confidential information that is legally privileged. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of any of the information contained in or attached to this transmission is STRICTLY PROHIBITED. If you have received this transmission in error, please immediately notify us by reply e-mail or by telephone at (650) 723-5548, and destroy the original transmission and its attachments without reading or saving in any manner. 

----- Original Message -----

**Comment by mpresteg** [comment]
Implemented sorting based upon relative frequency of likely haplotype pairs.
