### ISSUE TITLE
Detect HLADB(s) containing allele as CWD if specified HLADB does not list allele as CWD

### ISSUE THREAD

**Issue by mpresteg** [nmdp-bioinformatics/ImmunogeneticDataTools#26]
An example is:  DQA1*01:11 under HLADB 3.10

The software currently generates a warning saying this is not on the CWD list, as it is not found in CWD list for 3.10.  That allele was not added to the CWD list until 3.11.

However, if found in later version, report:
- First supported HLADB in which it appears?
- All supported HLADB(s) in which it appears?
- Or, leave as is and have user run using multiple HLADBs as input (no change)

Feedback requested from @kosoegawa.

**Comment by kosoegawa** [comment]
I would like to see:
DQA1*01:11 is not found in CWD list for HLADB 3.10
It is found in CWD list for HLADB 3.11 or later.

**Comment by mpresteg** [comment]
Implemented similar.
