### ISSUE TITLE
nonCwdWarnings.log

### ISSUE THREAD

**Issue by kosoegawa** [nmdp-bioinformatics/ImmunogeneticDataTools#30]
I used 3.11.0 database version.
In nonCwdWarnings.log, I got the following messages:

WARNING - Allele: HLA-DQB1_02:02 not in the CWD list for HLA DB: HLADB3110
WARNING - Allele: HLA-DPB1_09:01 not in the CWD list for HLA DB: HLADB3110

These alleles exist in CWD list.
Can you take a look what is going on?

**Comment by mpresteg** [comment]
I may have misinterpreted a response to a prior question.  It is coded to look for a strict (exact) match, not a by-position match.

I had asked the following question:  "I assume that I need to do a 'by position' comparison (2nd, 3rd or 4th position within the nomenclature) with the CWD alleles, as was the case when checking for the linkage disequilibrium.  Please confirm.".

After consulting with others, you responded on 4/30 with:  "Steve suggested differently." ...  "He suggested to use attached table to convert genotype data to a specific accession number. The user has to provide a specific database version that is used to generate HLA typing data. For example, I used 3.10 database for the data that we are using to test.
Then we look up a specific HLA allele in the specific database version to convert the allele name to be specific accession number. When accession number is obtained, then we look up CWD table using the accession number. If we find the accession number, then it is CWD.".

I took that to mean I should implement a strict match (not by-position).  Shall I change it?

**Comment by kosoegawa** [comment]
Please leave as it is now. I realized that the software that I am using have some issues with the database version. DQB1*02:02 is changed to DQB1*02:02:01 from 3.10.0 to 3.11.0. So, the software is working OK. The problem is the databases version in the HLA typing software. It looks like the software uses v3.10.0, but I see many alleles that appears from 3.11.0. So, I thought we are using 3.11.0. But apparently for these cases, these alleles are from 3.10.0. I will get back to you about this issue. Thanks!

**Comment by mpresteg** [comment]
Sure, will do.

Meanwhile, I've been trying to get a v0.3 of the software working that
deals appropriately with haplotypes and likely pairs (per Julia's
proposal).  This has been much more difficult than I expected.  However,
some progress this evening.  I'll see if I can have something to show you
both by next week.

-matt

**Comment by mpresteg** [comment]
@kosoegawa - May we consider this closed?

**Comment by kosoegawa** [comment]
Yes 

Kazu 

Confidential; Protected under State of California Evidence Code Section 1157 
CONFIDENTIALITY NOTICE: E-mail may contain confidential information that is legally privileged. Do not read this e-mail if you are not the intended recipient. This e-mail transmission, and any documents, files or previous e-mail messages attached to it may contain confidential information that is legally privileged. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of any of the information contained in or attached to this transmission is STRICTLY PROHIBITED. If you have received this transmission in error, please immediately notify us by reply e-mail or by telephone at (650) 723-5548, and destroy the original transmission and its attachments without reading or saving in any manner. 

----- Original Message -----
