### ISSUE TITLE
Rare Allele Pruning

### ISSUE THREAD

**Issue by mpresteg** [nmdp-bioinformatics/ImmunogeneticDataTools#31]
1.  Count total alleles found at a given locus, bail out if more than 7-20 (warning).
2.  Reduce to the protein level (if using protein based frequencies like NMDP).  Introduce another bail out for 5 protein level alleles found.  Make this configurable.
3.  Check reduced alleles against single locus frequency tables for existence

If all are true, construct haplotypes and look for linkages (as usual).

**Comment by mpresteg** [comment]
@JuliaUdell:  On item 3 - if there are 4 protein level alleles found, do I need existence of all 4 in the single locus frequency tables to proceed OR do I just proceed with whichever ones are found?

**Comment by biotronette** [comment]
Can you give me an example?

**Comment by mpresteg** [comment]
I no longer understand what I was asking here.  This is now implemented in a local version.  Will close this item when checked into the repository.
