### ISSUE TITLE
Delimited text output

### ISSUE THREAD

**Issue by biotronette** [nmdp-bioinformatics/ImmunogeneticDataTools#33]
Proposed output of GL string batch processing:

Column names; description

Sample ID; self-explanatory
nA; number of alleles in HLA-A ambiguity string (sum over both haplotypes)
nB, nC, nDRB1, etc.
nC1 linkages; number of Class 1 linkages found
nC2
C1 min L(genotype); minimum difference between haplotype likelihoods across all populations
C2 min L(genotype)

Notes: the last two columns are intended to capture instances where there is true haplotypic ambiguity given population frequency data (i.e. the most haplotypic ambiguity occurs in a population has a .35 likelihood for one combo and .65 for the other, with a difference of .3) - example forthcoming.

**Comment by mpresteg** [comment]
@JuliaUdell - Started on this.  An example for the last two columns will be useful.

**Comment by mpresteg** [comment]
No longer distinguishes between class I and class II.  Instead it will count the linkages and compute the minimum difference for each ld sought (bc, drb_dq, five_loc, six_loc, etc).

 - SampleID
 - nA alleles
 - nB Alleles
 - nC Alleles
 - nDRB1 Alleles
 - nDRB345 Alleles
 - nDQB1 Alleles
 - nLinkages found (per each linkage sought)
 - minSum (per each linkage sought)

**Comment by kosoegawa** [comment]
Please add header, so easy to understand what these numbers are.
