### ISSUE TITLE
Convert main via mvn exec to command line scripts

### ISSUE THREAD

**Issue by ghost** [nmdp-bioinformatics/ImmunogeneticDataTools#38]
With a command line argument parsing library (args4j, dsh-commandline, etc.), maven assembly plugin configuration, appassembler-maven-plugin configuration, and jdeb maven plugin configuration, the current main via `mvn exec` pattern could be converted to proper command line scripts installed via debian archive.

See e.g.
https://github.com/nmdp-bioinformatics/ngs/blob/master/tools/pom.xml
https://github.com/nmdp-bioinformatics/ngs/blob/master/tools/src/main/assembly/assembly.xml
https://github.com/nmdp-bioinformatics/ngs/tree/master/tools/src/deb
https://github.com/nmdp-bioinformatics/ngs/blob/master/tools/src/main/java/org/nmdp/ngs/tools/DownsampleFastq.java

**Comment by mhalagan** [comment]
I added command line tools in the most recent pull request (pull/56), but they may not be doing the same things as the mvn exec command. I'll work on making a command line tool that does the same thing.
