### ISSUE TITLE
Remove HaplotypePairs with no race overlap

### ISSUE THREAD

**Issue by mpresteg** [nmdp-bioinformatics/ImmunogeneticDataTools#42]
Pairs that don't have any race level frequencies in common cannot compute a relative frequency.

**Comment by mpresteg** [comment]
Working as expected post re-factor.  Repaired locally.

**Comment by kosoegawa** [comment]
Hi Matt,

Could you send me the output for review?

Kazu

Kazutoyo Osoegawa, Ph.D.
Senior Research Scientist, Department of Pathology
Histocompatibility, Immunogenetics & Disease Profiling Laboratory
Stanford University School of Medicine
3155 Porter Drive, Ste 2114A
Palo Alto CA 94304
Tel: 650-724-0169
Fax: 650-724-0294
Email: kazutoyo@stanford.edumailto:kazutoyo@stanford.edu

Confidential; Protected under State of California Evidence Code Section 1157
CONFIDENTIALITY NOTICE: E-mail may contain confidential information that is legally privileged. Do not read this e-mail if you are not the intended recipient. This e-mail transmission, and any documents, files or previous e-mail messages attached to it may contain confidential information that is legally privileged. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of any of the information contained in or attached to this transmission is STRICTLY PROHIBITED. If you have received this transmission in error, please immediately notify us by reply e-mail or by telephone at (650) 723-5548, and destroy the original transmission and its attachments without reading or saving in any manner.
