### ISSUE TITLE
Unusual linkage row in reference data set

### ISSUE THREAD

**Issue by mpresteg** [nmdp-bioinformatics/ImmunogeneticDataTools#6]
The BC linkage reference data set (http://en.wikiversity.org/wiki/HLA/Linkage_Disequilibrium/B-C_Blocks) contains the following:

B_07:02:01  DRB1_15:14  3.2     

Presumably, this is meant to be C instead of DRB1.  Please verify.  If so, we can change the local BCLinkageDisequilibrium.txt.

Eventually, we intend to use a more robust data set, but logging this issue in any case.

**Comment by kosoegawa** [comment]
I think this is an error. Please delete this line. This is weird. It is better not to spend much time to chasing something weird.

**Comment by mpresteg** [comment]
Resolved.  Invalid line removed.
