### ISSUE TITLE
Request for "WARNING - Linkage Not Found"

### ISSUE THREAD

**Issue by mpresteg** [nmdp-bioinformatics/ImmunogeneticDataTools#7]
Current code will report if no linkages are found whatsoever.  Inferred from recent comments that a WARNING for each allele that does not find a linkage is desirable.  Please confirm.

**Comment by kosoegawa** [comment]
Yes.
In perfect world, we would find 4 linkages.
2 B-C linkages
2 DR-DQ linkages
It is good to report if we failed to find any of the linkages.

**Comment by mpresteg** [comment]
@kosoegawa It seems we can get up to 2 or more possible linkages at B-C and DR-DQ.  So, I've implemented it such that if I find less than 2 at B-C or DR-DQ, it will complain of a missing linkage.  If you can confirm this behavior, I will check in and close this issue.

**Comment by kosoegawa** [comment]
I think it is OK to use the counted numbers.  I need to review several results. The only conceivable problem of this approach would be when we have "homozygous" allele. In this case I think we would have false warning.
Basically, we would like to find at least one or more combination for each HLA-B and HLA-DRB1 allele. In other words, we would like to flag to an allele that has no partner of HLA-C or HLA-DRB3/4/5 and HLA-DQ.

**Comment by mpresteg** [comment]
@kosoegawa I'll check it in as is, so you can review some results.  We can log a separate issue to deal with the homozygous case if/as needed.  

Note that I updated the readme with some instructions on how to run the set you provided me in San Diego (without running all of the other tests).  So, you can do:
- git pull
- mvn compile package
- mvn exec:java -Dexec.mainClass="org.dash.valid.LinkageDisequilibriumLoader" -Dexec.args="resources/test/stanfordExamples.txt"

The output will print to linkages.log (probably defaulting to your home directory).  I'll send some output (via email) in case you have trouble running it yourself.

**Comment by kosoegawa** [comment]
I found the following example:
Mar 13, 2015 2:57:56 PM org.dash.valid.LinkageDisequilibriumWriter reportDetectedLinkages
INFO: Your GL String: HLA-A*01:01:01:01+HLA-A*24:02:01:01/HLA-A*24:02:01:03^HLA-B*08:01:01/HLA-B*08:18/HLA-B*08:39/HLA-B*08:92/HLA-B*08:93+HLA-B*35:02:01/HLA-B*35:211^HLA-C*04:01:01:01/HLA-C*04:01:01:02/HLA-C*04:01:01:03/HLA-C*04:01:01:04/HLA-C*04:01:01:05/HLA-C*04:20/HLA-C*04:117+HLA-C*07:01:01:01/HLA-C*07:01:01:02/HLA-C*07:01:31/HLA-C*07:103/HLA-C*07:230^HLA-DPA1*01:03:01:01/HLA-DPA1*01:03:01:02/HLA-DPA1*01:03:01:03/HLA-DPA1*01:03:01:04/HLA-DPA1*01:03:01:05+HLA-DPA1*02:01:01^HLA-DPB1*02:01:02+HLA-DPB1*17:01^HLA-DQA1*02:01+HLA-DQA1*05:01:01:01/HLA-DQA1*05:01:01:02^HLA-DQB1*02:01:01+HLA-DQB1*02:02^HLA-DRB1*03:01:01:01/HLA-DRB1*03:01:01:02+HLA-DRB1*07:01:01:01/HLA-DRB1*07:01:01:02^HLA-DRB3*01:01:02:01/HLA-DRB3*01:01:02:02^HLA-DRB4*01:03:01:01/HLA-DRB4*01:03:01:03

We found partial linkages:
B Locus: HLA-B*08:01:01
C Locus: HLA-C*07:01:01
NegLocFreq: 0.9
Notes:  

We found perfect linkages:
B Locus: HLA-B*08:01:01
C Locus: HLA-C*04:01:01:01
NegLocFreq: 3.5
Notes:  

We found perfect linkages:
B Locus: HLA-B*35:02:01
C Locus: HLA-C*04:01:01:01
NegLocFreq: 2.1
Notes:  

We found perfect linkages:
DRB1 Locus: HLA-DRB1*07:01:01:01
DRB345 Locus: HLA-DRB4*01:03:01:01
DQA1 Locus: HLA-DQA1*02:01
DQB1 Locus: HLA-DQB1*02:02
NegLocFreq: 1.4
Notes:  

We found partial linkages:
DRB1 Locus: HLA-DRB1*07:01:01:01
DRB345 Locus: HLA-DRB4*01:03:01:02N
DQA1 Locus: HLA-DQA1*02:01
DQB1 Locus: HLA-DQB1*02:02
NegLocFreq: 3.5
Notes:

**Comment by kosoegawa** [comment]
The above example did not find DRB1_03:01:01:01/HLA-DRB1_03:01:01:02 linkage, but found two linkages for HLA-DRB1*07:01:01:01. So, this is not homozygous cases, but found the same number of counts as heterozygous.

**Comment by mpresteg** [comment]
I think I need more explanation here.  (1) Based on your most recent comments, are you suggesting that we should have generated a warning because the HLA-DRB1*03:01:01:01/HLA-DRB1*03:01:01:02 linkage wasn't found and two linkages were found for the HLA-DRB1*07 allele group?  (2) Put another way, if we detect multiple linkages for the same allele group, it should only 'count' as 1?  (3) Or, do we need to look at the specific HLA protein level?

**Comment by kosoegawa** [comment]
Multiple linkage is OK. This is not a problem. We will find a lot of multiple linkages. It is not clear to me whether we have no warning when we have "four" linkage counts or or more. I think expecting "4" linkages may not work. For example, we found four linkages, but we are missing one.
We need to have a warning if we could not find a linkage. I think this is false negative.
DRB1*03:01:01:01-DRB3*01:01:02:01-DQA1*05:01:01-DQB*02:01:01 exists in the lookup table.
The program could not find the linkage. I think because DQA1 is reported as "HLA-DQA1*05:01:01:01 (four field)", not DQA1*05:01:01 (three field).

**Comment by mpresteg** [comment]
I had implemented logic to handle 3 field vs. 4 field comparison, and made it robust some time ago.  However, I only completed that implementation for B-C until earlier tonight.  After my latest check-in (including the DR-DQ), it now produces a different output.  Confirm this is what you expect and I can close this issue:

Mar 13, 2015 11:37:40 PM org.dash.valid.LinkageDisequilibriumWriter reportDetectedLinkages
INFO: Your GL String: HLA-A*01:01:01:01+HLA-A*24:02:01:01/HLA-A*24:02:01:03^HLA-B*08:01:01/HLA-B*08:18/HLA-B*08:39/HLA-B*08:92/HLA-B*08:93+HLA-B*35:02:01/HLA-B*35:211^HLA-C*04:01:01:01/HLA-C*04:01:01:02/HLA-C*04:01:01:03/HLA-C*04:01:01:04/HLA-C*04:01:01:05/HLA-C*04:20/HLA-C*04:117+HLA-C*07:01:01:01/HLA-C*07:01:01:02/HLA-C*07:01:31/HLA-C*07:103/HLA-C*07:230^HLA-DPA1*01:03:01:01/HLA-DPA1*01:03:01:02/HLA-DPA1*01:03:01:03/HLA-DPA1*01:03:01:04/HLA-DPA1*01:03:01:05+HLA-DPA1*02:01:01^HLA-DPB1*02:01:02+HLA-DPB1*17:01^HLA-DQA1*02:01+HLA-DQA1*05:01:01:01/HLA-DQA1*05:01:01:02^HLA-DQB1*02:01:01+HLA-DQB1*02:02^HLA-DRB1*03:01:01:01/HLA-DRB1*03:01:01:02+HLA-DRB1*07:01:01:01/HLA-DRB1*07:01:01:02^HLA-DRB3*01:01:02:01/HLA-DRB3*01:01:02:02^HLA-DRB4*01:03:01:01/HLA-DRB4*01:03:01:03

We found partial linkages:
B Locus: HLA-B*08:01:01
C Locus: HLA-C*07:01:01
NegLocFreq: 0.9
Notes:  

We found perfect linkages:
B Locus: HLA-B*08:01:01
C Locus: HLA-C*04:01:01:01
NegLocFreq: 3.5
Notes:  

We found perfect linkages:
B Locus: HLA-B*35:02:01
C Locus: HLA-C*04:01:01:01
NegLocFreq: 2.1
Notes:  

We found partial linkages:
DRB1 Locus: HLA-DRB1*03:01:01:01
DRB345 Locus: HLA-DRB3*01:01:02:01
DQA1 Locus: HLA-DQA1*05:01:01
DQB1 Locus: HLA-DQB1*02:01:01
NegLocFreq: 1.1
Notes: Associated with B8

We found perfect linkages:
DRB1 Locus: HLA-DRB1*07:01:01:01
DRB345 Locus: HLA-DRB4*01:03:01:01
DQA1 Locus: HLA-DQA1*02:01
DQB1 Locus: HLA-DQB1*02:02
NegLocFreq: 1.4
Notes:

**Comment by kosoegawa** [comment]
Yes, this is what I expected. I executed "git pull" in my server, but I did not get the same results. Is the update on your local computer?

**Comment by mpresteg** [comment]
git pull will update the code base.  Did you run the maven build (mvn compile package) or re-execute the test set as well (mvn exec:java -Dexec.mainClass="org.dash.valid.LinkageDisequilibriumLoader" -Dexec.args="resources/test/stanfordExamples.txt")?  You would need to get new results.  Also note, I closed another issue in which it was requested that I move the logging from the executors home directory and into the 'current' directory where the command was run.  So, if you did run the test set, maybe you were still looking at the 'old' logs.

**Comment by kosoegawa** [comment]
Fixed. I forgot to run "mvn compile package".

**Comment by kosoegawa** [comment]
I will review the existing test results. Does the program work if I try to use different data set by replacing stanfordExamples.txt to something else in the command line argument?

**Comment by mpresteg** [comment]
Yes.  Provide a path to a different file.  The expected format is GL Strings separated by newline characters.  Note that the output appends to the existing log, so your results will be towards the bottom of the log file.  If you find that distracting, just remove the log file before each run so as to get output strictly dedicated to your last test run.  Feel free to provide some feedback about preferred output format or behavior.  I haven't implemented any log rotation strategy yet.
