### ISSUE TITLE
haplotypes and their frequencies are inconsistent in summary.xml

### ISSUE THREAD

**Issue by kosoegawa** [nmdp-bioinformatics/ImmunogeneticDataTools#80]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<gl-freq frequency-set="Inputted" id="SBCFMW0416" hladb="3.25.0">
    <gl-string>HLA-A*11:01:01:01~HLA-C*07:02:01:01~HLA-B*39:06:02~HLA-DRB4*01:03:01:01/HLA-DRB4*01:03:01:03~HLA-DRB1*04:01:01:01~HLA-DQA1*03:01:01~HLA-DQB1*03:02:01~HLA-DPA1*01:03:01:02~HLA-DPB1*04:01:01:01+HLA-A*01:01:01:01~HLA-C*07:01:01:01~HLA-B*08:01:01:01~HLA-DRB3*01:01:02:01~HLA-DRB1*03:01:01:01/HLA-DRB1*03:01:01:02~HLA-DQA1*05:01:01:02~HLA-DQB1*02:01:01~HLA-DPA1*02:01:01:02~HLA-DPB1*09:01:01</gl-string>
    <non-cwd>HLA-DPA1*02:01:01:02</non-cwd>
    <haplo-pair>
        <haplotype1 value="HLA-A*01:01g~HLA-C*07:01g~HLA-B*08:01g~HLA-DRB3*01:01~HLA-DRB1*03:01~HLA-DQB1*02:01g"/>
        <haplotype2 value="HLA-A*11:01g~HLA-C*07:02g~HLA-B*39:06~HLA-DRB4*01:01g~HLA-DRB1*04:01~HLA-DQB1*03:02g"/>
        <frequencies race="CAU">
            <frequency>8.881723421494385E-7</frequency>
            <relative-frequency>100.0</relative-frequency>
            <hap1-frequency>1.49532637579E-5</hap1-frequency>
            <hap1-rank>5701.0</hap1-rank>
            <hap2-frequency>0.0593965542592804</hap2-frequency>
            <hap2-rank>1.0</hap2-rank>
        </frequencies>
        <frequencies race="EURCAU">
            <frequency>5.439872647146341E-7</frequency>
            <relative-frequency>100.0</relative-frequency>
            <hap1-frequency>8.3350546331E-6</hap1-frequency>
            <hap1-rank>7715.0</hap1-rank>
            <hap2-frequency>0.0652649908921248</hap2-frequency>
            <hap2-rank>1.0</hap2-rank>
        </frequencies>
    </haplo-pair>
</gl-freq>

In this example, <haplotype1> corresponds <hap-2-frequency>, <haplotype2> should be <hap1-frequency> when I reviewed haplotypes.log file.
Can you make this information to be consistent?

**Comment by mpresteg** [comment]
Could you provide a bit more info?  There isn't a haplotypes.log file.  Did you mean haplotypePairs.log?  Perhaps you could attach the files that are in disagreement to this issue (as part of a new comment).  Also, specifying what you ran on the command line will also help in troubleshooting.

**Comment by kosoegawa** [comment]
My mistake. It should be linkages.log

**Comment by mpresteg** [comment]
Repaired in local repository.  Available for testing at:  https://github.com/mpresteg/ImmunogeneticDataTools/releases/latest

**Comment by mpresteg** [comment]
Finally merged Heidelberg DaSH changes
