### ISSUE TITLE
linkages.log file

### ISSUE THREAD

**Issue by kosoegawa** [nmdp-bioinformatics/ImmunogeneticDataTools#81]
Can you re-organize the order of genes in linkages.log file? It is easier to review the results if the order of the genes are organized in the same way as the haplotypes.

Currently, the order of the genes are as follows:
DRB345 Locus: [HLA-DRB3*01:01]
A Locus: [HLA-A*01:01g]
DRB1 Locus: [HLA-DRB1*03:01]
C Locus: [HLA-C*07:01g]
B Locus: [HLA-B*08:01g]
DQB1 Locus: [HLA-DQB1*02:01g]

Please order as follows:
A Locus: [HLA-A*01:01g]
C Locus: [HLA-C*07:01g]
B Locus: [HLA-B*08:01g]
DRB345 Locus: [HLA-DRB3*01:01]
DRB1 Locus: [HLA-DRB1*03:01]
DQB1 Locus: [HLA-DQB1*02:01g]

Alternatively, you could represent this using glstring as follows:
HLA-A*01:01g~HLA-C*07:01g~HLA-B*08:01g~HLA-DRB3*01:01~HLA-DRB1*03:01~HLA-DQB1*02:01g

This would make a lot easier to compare. We need to validate data in each file.

**Comment by kosoegawa** [comment]
When posted, start separator '* disappeared in the previous comments.'

**Comment by mpresteg** [comment]
Repaired in local repository.  Available for testing at:  https://github.com/mpresteg/ImmunogeneticDataTools/releases/latest

**Comment by mpresteg** [comment]
Finally merged Heidelberg DaSH changes
