### ISSUE TITLE
NMDP code

### ISSUE THREAD

**Issue by kosoegawa** [nmdp-bioinformatics/ImmunogeneticDataTools#82]
It would be great if we could submit the GL string with NMDP code. We obtain SSO typing with NMDP code.
High resolution NGS data: HLA-A*01:01:01:01+HLA-A*11:01:01:01
Low Resolution SSO typing data: HLA-A*01:PWKH+HLA-A*11:PWWK
NMDP code conversion table can be found: https://bioinformatics.bethematchclinical.org/HLA/numeric.v3.zip

This will give us more flexibility for the software.

**Comment by mpresteg** [comment]
Repaired in local repository.  Get latest release (from that repository) here:  https://github.com/mpresteg/ImmunogeneticDataTools/releases/latest

**Comment by mpresteg** [comment]
Finally merged Heidelberg DaSH changes
