### ISSUE TITLE
add <sample> in summary.xml

### ISSUE THREAD

**Issue by kosoegawa** [nmdp-bioinformatics/ImmunogeneticDataTools#83]
Currently,
\<gl-freq frequency-set="Inputted" id="SBCFMW0416" hladb="3.25.0"\>
\</gl-freq\>

Can you separate sample ID as follows?
\<sample id="SBCFMW0416"\>
    \<gl-freq frequency-set="Inputted" hladb="3.25.0"\>
    \</gl-freq\>
\</sample\>

**Comment by mpresteg** [comment]
Repaired in local repository.  Get latest release (from that repository) here:  https://github.com/mpresteg/ImmunogeneticDataTools/releases/latest

**Comment by mpresteg** [comment]
Finally merged Heidelberg DaSH changes
